# Generated by Django 4.0.4 on 2022-05-03 11:17

from django.db import migrations, models

from urlshortner import urlapp
from urlshortner.urlapp import models
from datetime import datetime, timedelta
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('urlapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='Linkinfo',
            name='short_link',
        ),
        migrations.AddField(
            model_name='Linkinfo',
            name='expire_date',
            field=models.DateTimeField(default=urlapp.models.get_expire_date),
        ),
        migrations.AddField(
            model_name='Linkinfo',
            name='short_link',
            field=models.CharField(max_length=8, default=urlapp.models.get_short),
        ),
        migrations.AlterField(
            model_name='Linkinfo',
            name='link',
            field=models.URLField(max_length=10000),
        ),
    ]
